# TiDB Configuration.

compatible-kill-query = true
enable-streaming = false
host = "0.0.0.0"
lease = "45s"
lower-case-table-names = 2
oom-action = "log"
run-ddl = true
socket = ""
split-table = true
store = "tikv"
token-limit = 1000

[log]
disable-timestamp = false
expensive-threshold = 10000
format = "text"
level = "warn"
query-log-max-len = 2048
slow-threshold = 300

[log.file]
log-rotate = true
max-backups = 0
max-days = 0
max-size = 300

[security]
cluster-ssl-ca = ""
cluster-ssl-cert = ""
cluster-ssl-key = ""
ssl-ca = ""
ssl-cert = ""
ssl-key = ""

[status]
report-status = true
status-port = 10080
metrics-addr = "192.168.173.100:9091"
metrics-interval = 15


[performance]
cross-join = true
feedback-probability = 0.0
force-priority = "NO_PRIORITY"
max-procs = 0
pseudo-estimate-ratio = 0.8
query-feedback-limit = 1024
run-auto-analyze = false
stats-lease = "3s"
stmt-count-limit = 5000
tcp-keep-alive = true

[proxy-protocol]
header-timeout = 5
networks = ""

[prepared-plan-cache]
capacity = 100
enabled = true

[metric]
address = "192.168.173.100:9091"
interval = "15s"
job = "tidb"

[opentracing]
enable = false
rpc-metrics = false

[opentracing.reporter]
buffer-flush-interval = 0
local-agent-host-port = ""
log-spans = false
queue-size = 0

[opentracing.sampler]
max-operations = 0
param = 1.0
sampling-refresh-interval = 0
sampling-server-url = ""
type = "const"

[tikv-client]
commit-timeout = "41s"
grpc-connection-count = 16
grpc-keepalive-time = 10
grpc-keepalive-timeout = 3

[txn-local-latches]
capacity = 10240000
enabled = false

[binlog]
enable=true
ignore-error = false
write-timeout = "15s"
