# TiKV config template
#  Human-readable big numbers:
#   File size(based on byte): KB, MB, GB, TB, PB
#    e.g.: 1_048_576 = "1MB"
#   Time(based on ms): ms, s, m, h
#    e.g.: 78_000 = "1.3m"

log-level = "info"

[readpool.storage]
high-concurrency = 8
low-concurrency = 2
normal-concurrency = 8

[readpool.coprocessor]
high-concurrency = 8
low-concurrency = 2
normal-concurrency = 8

[server]
grpc-concurrency = 8
# labels = { zone = "qsh", host = "tikv169", rack = "C02" }

[storage]

[pd]
# This section will be overwritten by command line parameters

[metric]
address = "192.168.173.100:9091"
interval = "15s"
job = "tikv"

[raftstore]
raftdb-path = ""
sync-log = false

[coprocessor]

[rocksdb]
max-background-jobs = 3
max-sub-compactions = 1
wal-dir = ""

[rocksdb.defaultcf]
block-cache-size = "512MB"
max-compaction-bytes = "128MB"

[rocksdb.lockcf]
block-cache-size = "128MB"

[rocksdb.writecf]
block-cache-size = "512MB"

[raftdb]

[raftdb.defaultcf]
block-cache-size = "128MB"

[security]
ca-path = ""
cert-path = ""
key-path = ""

[import]
